# Generated by Django 4.2 on 2023-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rates', '0003_alter_currency_options_alter_exchangerate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Exchange rate'),
        ),
    ]
