# Generated by Django 4.2 on 2023-04-12 04:40

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_default_categories(apps, schema_editor) -> None:
    """Generate default categories for all users."""
    Category = apps.get_model("transactions", "Category")
    categories = [
        {
            "name": _("Food & Beverage"),
            "is_income": False,
        },
        {
            "name": _("Rentals"),
            "is_income": False,
        },
        {
            "name": _("Transportation"),
            "is_income": False,
        },
        {
            "name": _("Personal Items"),
            "is_income": False,
        },
        {
            "name": _("Education"),
            "is_income": False,
        },
        {
            "name": _("Fitness"),
            "is_income": False,
        },
        {
            "name": _("Debt"),
            "is_income": True,
        },
        {
            "name": _("Loan"),
            "is_income": False,
        },
        {
            "name": _("Salary"),
            "is_income": True,
        },
        {
            "name": _("Outgoing transfer"),
            "is_income": False,
        },
        {
            "name": _("Incoming transfer"),
            "is_income": True,
        },
    ]

    category_data = [
        Category(name=category["name"], is_income=category["is_income"])
        for category in categories
    ]

    Category.objects.bulk_create(category_data)


def delete_default_categories(apps, schema_editor) -> None:
    """Delete all default data in Category when revert migration."""
    Category = apps.get_model("transactions", "Category")
    Category.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
        create_default_categories,
        reverse_code=delete_default_categories,
        ),
    ]
