# Generated by Django 4.2 on 2023-04-27 08:16

import apps.transactions.models.transaction
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_migrate_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[apps.transactions.models.transaction.validate_positive], verbose_name='Amount'),
        ),
    ]
