# Generated by Django 4.2 on 2023-05-18 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tagged_friends',
            field=models.ManyToManyField(related_name='tagged_friends', through='transactions.SharedBill', to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
