# Generated by Django 4.2 on 2023-05-19 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_transaction_tagged_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tagged_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_friends', through='transactions.SharedBill', to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
