# Generated by Django 4.2 on 2023-05-31 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0005_alter_transaction_tagged_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='code',
            field=models.CharField(default='', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Code must be at most 4 uppercase letters.')], verbose_name='Code'),
        ),
    ]
