# Generated by Django 4.2 on 2023-04-18 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                default="VND", max_length=3, verbose_name="Default currency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Friends",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Premium status"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="+84000000000",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be in the format "+84xxxxxxxxx".',
                        regex="^\\+84[0-9]{9}$",
                    ),
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="transaction_count",
            field=models.IntegerField(default=0, verbose_name="Transaction count"),
        ),
        migrations.AddField(
            model_name="user",
            name="transaction_streak",
            field=models.IntegerField(default=0, verbose_name="Transaction streak"),
        ),
    ]
