# Generated by Django 4.2 on 2023-04-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_user_date_of_birth_user_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_information',
            field=models.BooleanField(default=False, verbose_name='Updated information'),
        ),
    ]
