# Generated by Django 4.2 on 2023-05-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_updated_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sender', to=settings.AUTH_USER_MODEL, verbose_name='From user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_receiver', to=settings.AUTH_USER_MODEL, verbose_name='To user')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(related_name='friends', through='users.Friendship', to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
