# Generated by Django 4.2 on 2023-05-17 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_remove_user_friends_friendship_user_friend_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friend_list',
            new_name='friends',
        ),
    ]
